-- 범용 변경이력 (Oracle)
-- HIST_EVENT: 누가/언제/어느 테이블/어떤 액션
-- HIST_SNAPSHOT: 변경 전(before) / 변경 후(after) 스냅샷(CLOB JSON)

CREATE TABLE HIST_EVENT (
    HIST_ID        NUMBER(19)     NOT NULL,
    ENTITY_TYPE    VARCHAR2(50)   NOT NULL,  -- 업무구분: MEMBER, FILE ...
    TABLE_NM       VARCHAR2(100),            -- 실제 테이블명(선택): MEMBER ...
    ENTITY_ID      VARCHAR2(100)  NOT NULL,  -- 대상 PK
    ACTION_TYPE    VARCHAR2(10)   NOT NULL,  -- CREATE / UPDATE / DELETE
    ACTOR_ID       VARCHAR2(50),
    ACTOR_NM       VARCHAR2(100),
    REASON         VARCHAR2(500),
    REQ_IP         VARCHAR2(50),
    TRACE_ID       VARCHAR2(50),
    CHANGED_AT     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_HIST_EVENT PRIMARY KEY (HIST_ID)
);

CREATE SEQUENCE SEQ_HIST_EVENT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE INDEX IX_HIST_EVENT_01 ON HIST_EVENT (ENTITY_TYPE, ENTITY_ID, CHANGED_AT);
CREATE INDEX IX_HIST_EVENT_02 ON HIST_EVENT (TABLE_NM, CHANGED_AT);

CREATE TABLE HIST_SNAPSHOT (
    HIST_ID        NUMBER(19)     NOT NULL,
    BEFORE_DATA    CLOB,                     -- 변경 전 JSON
    AFTER_DATA     CLOB,                     -- 변경 후 JSON
    CONSTRAINT PK_HIST_SNAPSHOT PRIMARY KEY (HIST_ID),
    CONSTRAINT FK_HIST_SNAPSHOT FOREIGN KEY (HIST_ID) REFERENCES HIST_EVENT (HIST_ID)
);

COMMENT ON TABLE  HIST_EVENT              IS '범용 변경이력 헤더';
COMMENT ON COLUMN HIST_EVENT.ENTITY_TYPE  IS '업무/도메인 구분';
COMMENT ON COLUMN HIST_EVENT.TABLE_NM     IS '실제 변경 테이블명(선택)';
COMMENT ON COLUMN HIST_EVENT.ENTITY_ID    IS '대상 PK 문자열';
COMMENT ON COLUMN HIST_EVENT.ACTION_TYPE  IS 'CREATE/UPDATE/DELETE';
COMMENT ON TABLE  HIST_SNAPSHOT           IS '변경 전후 스냅샷';
COMMENT ON COLUMN HIST_SNAPSHOT.BEFORE_DATA IS '변경 전 JSON';
COMMENT ON COLUMN HIST_SNAPSHOT.AFTER_DATA  IS '변경 후 JSON';
